#!/usr/bin/env python3
"""Draws arch-pixel.png, the pixel-art Arch logo fastfetch shows in kitty.

Run from anywhere: python3 arch-pixel.py (needs python-pillow).

Size: each sprite pixel is 7x7 screen px. Kitty's cell with Departure Mono
at 22px is 14x28, so 7 divides both: the 48x48 canvas is exactly 336px =
24x12 cells, and kitty shows it 1:1 with no resampling. If kitty's font
size changes, PX must change with it (fastfetch's width/height too).

Shape: traced from the official logo (/usr/share/pixmaps/archlinux-logo.svg,
box-downsampled to 46x46), then cleaned by hand so the edges are even
stair steps. It keeps the real logo's details: the swoosh notch cut into
the left edge, the rounded arch in the base, the heavier right leg, and the
feet curling out to points. The swoosh is drawn as an engraved groove
("d" in the mask, solid dark orange) rather than cut out: a one-pixel slit
at this size only touches at its corners and reads as scattered holes.

Shading is worked out from the mask, lit from the top-left like a game
sprite: edges facing up/left get the light orange, edges facing down/right
the dark orange, the rest is Claude orange, and a crust drop shadow sits one
pixel down-right.
"""
from pathlib import Path
from PIL import Image

PX = 7
CANVAS = 48
LIGHT = (0xf5, 0x95, 0x75, 255)   # shimmer, the bar clock's orange
BODY = (0xd7, 0x77, 0x57, 255)    # Claude orange
DARK = (0xa6, 0x55, 0x3b, 255)    # Claude orange, darkened for the shade
SHADOW = (0x11, 0x11, 0x1b, 255)  # Mocha crust

MASK = """
......................#.......................
......................##......................
.....................###......................
.....................####.....................
.....................####.....................
....................######....................
....................######....................
...................#######....................
...................########...................
...................########...................
..................##########..................
..................##########..................
..................###########.................
.................#dd#########.................
.................##dd#########................
................####dd########................
...............######dd########...............
...............################...............
..............##################..............
..............##################..............
.............####################.............
.............####################.............
............######################............
............######################............
...........########################...........
...........########################...........
..........###########....###########..........
..........##########......##########..........
.........##########........##########.........
.........##########........##########.........
........##########..........##########........
.......###########..........##########........
.......###########..........###########.......
......############..........###########.......
......############..........###########.......
.....#############..........############......
.....#############..........############......
....#############............############.....
....#########...................##########....
...########........................########...
...######............................######...
..####.................................#####..
.####....................................###..
.##........................................##.
""".split()

assert all(len(row) == len(MASK[0]) for row in MASK), "ragged mask"
OFF = (CANVAS - len(MASK[0])) // 2  # centre the 46x44 logo on the canvas
cells = {(x + OFF, y + OFF + 1): c
         for y, row in enumerate(MASK) for x, c in enumerate(row) if c != "."}
filled = set(cells)


def colour(x, y):
    if cells[x, y] == "d":
        return DARK
    if (x - 1, y) not in filled or (x, y - 1) not in filled:
        return LIGHT
    if (x + 1, y) not in filled or (x, y + 1) not in filled:
        return DARK
    return BODY


img = Image.new("RGBA", (CANVAS * PX, CANVAS * PX), (0, 0, 0, 0))


def dot(x, y, rgba):
    img.paste(rgba, (x * PX, y * PX, (x + 1) * PX, (y + 1) * PX))


for x, y in filled:
    if (x + 1, y + 1) not in filled:
        dot(x + 1, y + 1, SHADOW)
for x, y in filled:
    dot(x, y, colour(x, y))

out = Path(__file__).with_name("arch-pixel.png")
img.save(out)
print(f"{out}: {CANVAS}x{CANVAS} sprite, {img.width}x{img.height}px, "
      f"{img.width // 14}x{img.height // 28} kitty cells")
