splash = false

wallpaper {
    monitor = HDMI-A-2
    path = /home/nier/Documents/Wallpapers/foggy-city.jpg
}

wallpaper {
    monitor = DP-3
    path = /home/nier/Documents/Wallpapers/knight-building.png
}

