# Catppuccin Mocha
background_color=#1e1e2e
timecode_color=#cdd6f4
title_color=#f59575
time_pos_color=#cdd6f4
time_pos_outline_color=#1e1e2e
buttons_color=#af87ff
small_buttonsL_color=#af87ff
small_buttonsR_color=#af87ff
top_buttons_color=#af87ff
held_element_color=#6c7086
