# Catppuccin Mocha
background_color=#1e1e2e
timecode_color=#cdd6f4
title_color=#f5e0dc
time_pos_color=#cdd6f4
time_pos_outline_color=#1e1e2e
buttons_color=#cba6f7
small_buttonsL_color=#cba6f7
small_buttonsR_color=#cba6f7
top_buttons_color=#cba6f7
held_element_color=#6c7086
